ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS privacy_accepted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS document_verification_status TEXT NOT NULL DEFAULT 'missing';
ALTER TABLE users ADD COLUMN IF NOT EXISTS document_type TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS document_last4 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS document_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS document_verified_at TIMESTAMPTZ;
